[project]
name = "pacman"
version = "0.1.0"
description = "Pacman clone 1337 project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mazegenerator",
    "numpy>=2.5.1",
    "pydantic>=2.13.4",
    "pygame>=2.6.1",
    "pyinstaller>=6.21.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.1.0-py3-none-any.whl" }

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.1.0",
]
